# current only support equihash

# gpu configures
# arrange this configurations as the output of nvidia-smi
devices:
  - id: 0
    model: evga-1080ti-sc2
    pwrcap: 250
  - id: 1
    model: evga-1070ti-sc
    pwrcap: 180
  - id: 2
    model: evga-1070ti-sc
    pwrcap: 180
  - id: 3
    model: evga-1080ti-ftw3
    pwrcap: 280
  - id: 4
    model: nvidia-1070-founder
    pwrcap: 150
  - id: 5
    model: evga-1080ti-sc2
    pwrcap: 250

wallets:
  btcz-miningspeed:
    server: us.miningspeed.com
    port: 3072
    address: t1YRhV4rtvnSN4YGPxyGJyaosopB31GrTT7.eva00
    pass: x
  sng-miningspeed:
    server: us.miningspeed.com
    port: 3022
    address: s1UANgfyVNjxAQMCC7sj7C78oN73NcBt1Jp.eva00
    pass: x        
  zec-flypool-bittrex: 
    server: eu1-zcash.flypool.org
    port: 3333
    address: t1QMNWFNGcJw4yJWm1md57QtVRnHeTcPxpf.eva00
    pass: x
  zec-flypool-binance:
    server: eu1-zcash.flypool.org
    port: 3333
    address: t1aLAzdsnMbxS3xMsGV2pUK66Ro58oLv1eD.eva00
    pass: x
  zen-suprnova:
    server: zen.suprnova.cc
    port: 3618
    address: yishanhe.eva00
    pass: x
  zcl-suprnova:
    server: zcl.suprnova.cc
    port: 4042
    address: yishanhe.eva00
    pass: x
  zcl-donation:
    server: pool.zclassic.org
    port: 2083
    address: t1Nncx9t9AJFq1LXoxkRE8YxZpoLxDJRNxK.eva00
    pass: x     

miners:
  zm: 
    location: ./miners/zm
    version: 0.5.8
    checksum: 
      sha1: 827b137e061fe1da8f8fbcea12cec22449d3ae13 
  ewbf: 
    location: ./miners/ewbf
    version: 0.3.4
  bminer:
    location: ./miners/bminer
    version: 5.3.0
    checksum:
      sha256: 6e742df803a99dfdb4505890344b21968185081e99b10a8cfc312886bce131be

runners:
  default:
    - miner: zm
      wallet: zec-flypool-binance
      devices:
        - 0
        - 5
    - miner: zm
      wallet: zcl-donation
      devices:
        - 3
        - 4     
    - miner: zm
      wallet: btcz-miningspeed
      devices:
        - 1 
    - miner: zm
      wallet: sng-miningspeed
      devices:
        - 2 
  two:
    - miner: zm
      wallet: zec-flypool-binance
      devices:
        - 1
        - 2
        - 4
    - miner: zm
      wallet: zcl-donation
      devices:
        - 0
        - 3
        - 5     
  three:
    - miner: zm
      wallet: zec-flypool-binance
      devices:
        - 1
        - 2
        - 4
    - miner: zm
      wallet: zcl-donation
      devices:
        - 0
        - 5
    - miner: zm
      wallet: zen-suprnova
      devices:
        - 3     
  zec-binance:
    - miner: zm
      wallet: zec-flypool-binance
      devices:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5


  

